from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from django.core.urlresolvers import reverse


#A Static Sitemap class. The items callable returns a list with url-entry names for all the static pages. the locations are generated by reversing the urlnames
class StaticViewSitemap(sitemaps.Sitemap):
    priority = 0.5
    changefreq = 'never'
   
    def items(self):
        return ['pages_about', 'pages_terms', 'pages_disclaimer','pages_contact']

    def location(self, item):
        return reverse(item)
